include:
# Sofle without dongle 不带dongle的Sofle
  # Sofle with oled display(with nice_oled module) 适用于带oled的Sofle
  - board: nice_nano_v2 
    shield: Sofle_left nice_oled
    snippet: studio-rpc-usb-uart 
    artifact-name: Sofle_left_oled
  - board: nice_nano_v2
    shield: Sofle_right nice_oled
    artifact-name: Sofle_right_oled
  # Sofle with nice!view display(with nice_view_custom module) 适用于带nice_view的Sofle
  - board: nice_nano_v2
    shield: Sofle_left Nice_view_config nice_view_custom
    snippet: studio-rpc-usb-uart
    artifact-name: Sofle_left_nice_view
  - board: nice_nano_v2
    shield: Sofle_right Nice_view_config nice_view_custom
    artifact-name: Sofle_right_nice_view


#Sofle with dongle 带dongle的Sofle
  # dongle with LCD display 带LCD显示的dongle
  - board: nice_nano_v2
    shield: Sofle_dongle_central dongle_screen
    snippet: studio-rpc-usb-uart
    artifact-name: Sofle_central_dongle
  # peripheral with oled display(with nice_oled module)
  - board: nice_nano_v2
    shield: Sofle_dongle_left nice_oled
    artifact-name: Sofle_peripheral_left_oled
  - board: nice_nano_v2
    shield: Sofle_dongle_right nice_oled
    artifact-name: Sofle_peripheral_right_oled   
  # peripheral with nice!view display(with nice_view_custom module)
  - board: nice_nano_v2
    shield: Sofle_dongle_left Nice_view_config nice_view_custom
    artifact-name: Sofle_peripheral_left_nice_view
  - board: nice_nano_v2
    shield: Sofle_dongle_right Nice_view_config nice_view_custom
    artifact-name: Sofle_peripheral_right_nice_view
 
  - board: nice_nano_v2
    shield: settings_reset